project:
  type: website
  output-dir: docs

website:
  title: "A learner's Blog"
  description: "Heikos personal Weblog"
  site-url: https://hstaudt.github.io
  
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: rss
        href: blog.xml
      - icon: github
        href: https://github.com/hstaudt
      - icon: mastodon
        href: https://mastodon.social/@hstd
format:
  html:
    theme: cosmo
    css: styles.css



