project:
  type: website

website:
  title: "A learner's Blog"
  description: "Heikos personal Weblog"
  site-url: https://hstaudt.github.io
  
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: mastodon
        href: https://mastodon.social
format:
  html:
    theme: cosmo
    css: styles.css



